### ISSUE TITLE
Cloning and changing name

### ISSUE THREAD

**Issue by axelsegebrecht** [netlify/victor-hugo#10]
Thank you, for creating this 👍 

Just a quick issue I am having with NPM:

- I cloned the repo (actually tried both ZIP and git clone)
- Renamed the repo to something else for my project
- Ran npm install and got following error:
"npm WARN victor-hugo@1.0.0 No repository field."

Basically, unless I leave the name of the folder the repo is in the same as 'victor-hugo' I cannot build anything.

**Comment by calavera** [comment]
That's very weird, which version of NPM are you using?

**Comment by calavera** [comment]
Hey @axelsegebrecht. I'm closing this issue because we haven't seen any movement here. Other people are using victor-hugo without bumping into this issue. Please, feel free to reopen if you still is worth investigate it again.
