### ISSUE TITLE
Build fails, when deploying to Netlify

### ISSUE THREAD

**Issue by mgrandl** [netlify/victor-hugo#12]
So I just build a site using Victor Hugo and if I try to deploy a version where I am rendering {{ .Content }} on the index.html I am getting an error:

> ERROR: 2017/01/09 23:55:08 template.go:132: template: partials/text.html:4:3: executing "partials/text.html" at <.Content>: can't evaluate field Content in type *hugolib.Node in partials/text.htm

So my guess is that, since including {{ .Content }} on the index.html file is a feature only implemented in Hugo v0.18 that there is an old version running on Netlify?

**Comment by calavera** [comment]
We're still running Hugo 0.17 by default. 0.18 changed so much that we didn't want to force all our user to migrate. You can still run Hugo 0.18 on Netlify thought, you need to change the build command to use `hugo_0.18` rather than `hugo`.

Please, let me know if that work.

**Comment by mgrandl** [comment]
Cool thanks for the quick answer! Since I am deploying using the "npm run build" command, how would I specify the hugo_0.18 version?

**Comment by calavera** [comment]
I think you only need to change it here:

https://github.com/netlify/victor-hugo/blob/master/gulpfile.babel.js#L12

**Comment by mgrandl** [comment]
Alright yeah I am in the process of writing a netlify specific build script. I'll let you know how it went!

**Comment by mgrandl** [comment]
Worked thanks!
