### ISSUE TITLE
[[FEATURE]] change source organization so that "victorhugo" is a theme...

### ISSUE THREAD

**Issue by rdwatters** [netlify/victor-hugo#13]
Not including bug report since this is more of a "feature" request.

I think there is value in making "victorhugo" the theme in the `site` directory. I appreciate the conflation of webpack and hugo's typical source organization since it gives a one-liner to get up and running from the command line, but Hugo's baked-in theming is awfully handy, and I can see people using Victor Hugo from the get go as a theme that can repurposed or shared rather than a standalone site. In other words...

```
/site/
    content/
    themes/
        victorhugo/
         All the VH goodies netlify has put together with webpack, etc.
```

As an aside, netlify is f*(&(*& awesome. Thanks!

**Comment by tech4him1** [comment]
Are you guys thinking of doing this eventually, or not?

**Comment by calavera** [comment]
not at this point, but we can consider it further is someone opens a pull request with the necessary changes to make it work 😉

**Comment by calavera** [comment]
the good thing about being a standalone setup is that it includes a lot of helpful commands that would not be available if it were a theme. Hugo's themes only affect the content, but you cannot add commands with them, as far as I know.

**Comment by rdwatters** [comment]
> the good thing about being a standalone setup is that it includes a lot of helpful commands that would not be available if it were a theme. Hugo's themes only affect the content, but you cannot add commands with them, as far as I know.

That's a good point @calavera. 

I would think that `cd my-hugo-site` vs `cd my-hugo-site/themes/victorhugo` would be pretty easy to manage in the installation directions. Then just have the assets compiled go to the `themes/victor-hugo/static`. Part of the benefits of Hugo themes--and this is the real sell in some of the document changes I'm trying to make for Hugo---is that your `content/*.md` and `data/*{yml,toml,json}`  can remain independent of the theme while remaining compatible with the upstream...but then again, Victor Hugo is more of a starter kit than a theme. Hmmm...

All said, I may have worded this more strongly than I actually feel about it, haha. It's a cool tool and great that Netlify regularly maintains it. Thanks!

**Comment by tech4him1** [comment]
> Hugo's themes only affect the content, but you cannot add commands with them, as far as I know.
Yes, I've had the same problems trying to make my own Hugo theme.  How you guys have done it is probably the best way possible, as a "starter kit" is very useful.   Thanks!

**Comment by jhabdas** [comment]
> not at this point, but we can consider it further is someone opens a pull request with the necessary changes to make it work 😉

A likely story. Is this a wontfix?

**Comment by calavera** [comment]
Yes, this is a wontfix currently. Closing the issue.

**Comment by jhabdas** [comment]
Given Hugo is kindly [hosting their themes](https://github.com/spf13/hugoThemes/issues/139#issuecomment-294160445) on Netlify, this feels like it's worth a few minutes of someone at Netlify's time.
