### ISSUE TITLE
Suggest to remove Babel as dependency

### ISSUE THREAD

**Issue by walexy** [netlify/victor-hugo#15]
After going in circles trying to get Gulp to run with Babel I'm throwing in the towel. Now that Node v4+ supports a lot of ES2015 features could Babel be removed as a dependancy?
https://github.com/yeoman/generator-webapp/issues/356

**Bug**
**Executing NPM Start throws an error**
`Requiring external module babel-core/register`

- MacOS
- Hugo v0.19
- NPM 4.4.1
- NodeJS 6.10.0
- Gulp 
    - CLI version 3.9.0
    - Local version 3.9.0

**Comment by calavera** [comment]
I think that's possible, I'm not against reducing the number of moving parts this project needs to run.

**Comment by jhabdas** [comment]
Kill WebPack too while your at it.

**Comment by calavera** [comment]
Hey, thanks for the suggestion. We'll take any improvements in the projects in Pull Request form, where we can discuss the merits and advantages of the changes. For the time being, I'm going to close this issue.
