### ISSUE TITLE
Use Block Template Layout Inheritance

### ISSUE THREAD

**Issue by jhabdas** [netlify/victor-hugo#19]
Hugo introduced block templates in v0.16. Unlike what's possible in Jekyll and other SSGs, block templates afford users the ability to create extensible layouts and maintain a DRY approach to creating pages. Block templates help prevent bugs, improve thematic consistency across pages, reduce the total number of lines of code as a site grows and improves developer experience.

I consider Block Templates a best practice approach in Hugo. Would love this implemented in Victor Hugo for the benefit of its users.

**Documentation**
https://www.gohugo.io/templates/blocks/

**Example Implementation**
https://github.com/comfusion/after-dark/blob/master/layouts/_default/baseof.html

**Comment by rdwatters** [comment]
@calavera If you think this is worthwhile, I can submit a PR this weekend. I might suggest some other changes as well, but I also appreciate you guys have [tutorials](https://www.netlify.com/blog/2016/11/15/new-to-jamstack-how-to-make-a-site-from-a-to-z/) that were written before the addition of these more recent Hugo features. LMK how I can help...

**Comment by calavera** [comment]
> Would love this implemented in Victor Hugo for the benefit of its users.

There is nothing to implement in Victor Hugo. The very few markup in this repository is only a get started that people discard.

This is all the markup included in this project:

```
{{ partial "header" . }}

<h1>Hugo with Gulp, PostCSS and Webpack</h1>

{{ partial "footer" . }}
```

This project is not tied to any version of Hugo, therefore, this markup works with any version probably from the 0.1.0 release of Hugo.

**Comment by rdwatters** [comment]
> There is nothing to implement in Victor Hugo. The very few markup in this repository is only a get started that people discard.

Ahhh, gotcha.

> This project is not tied to any version of Hugo, therefore, this markup works with any version probably from the 0.1.0 release of Hugo.

`partials` weren't implemented until v0.12, but I know what you mean. Plus, it doesn't matter since you [guys are only supporting v13+](https://github.com/netlify/build-image/blob/master/Dockerfile#L184-L206). 

I'll take this as a "no thanks, Ryan" on submitting a PR this week with some of these newer Hugo features. 😆  

Regardless, thanks for actively maintaining such an awesome starter kit for Hugo and for the quick response @calavera!

**Comment by jhabdas** [comment]
> There is nothing to implement in Victor Hugo.

Curious to hear more about why you feel this way, David. This starter kit gives opinion by way of its implementation. And the current implementation could be improved using block templates. 

An alternative could be to remove the Hugo template provided and add support automated Hugo theme installation. After Dark, for example, is available via NPM and is semantically versioned.

**Comment by jhabdas** [comment]
Not interested in pursuing this further. I don't see a lot of value attempting to build best practices into something using Webpack.
