### ISSUE TITLE
NPM task does not exist

### ISSUE THREAD

**Issue by kalinchernev** [netlify/victor-hugo#20]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Run `npm run webpack` targeting `"webpack": "gulp webpack"`

**- If the current behavior is a bug, please provide the steps to reproduce.**
Use the force and the CLI.

**- What is the expected behavior?**
I don't know really - having both gulp and webpack at the same time for achieving similar things, I don't know what were your objectives with this task.

**- Please mention your node.js, NPM, Hugo and operating system version.**
Irrelevant, it's just a non-existent gulp task.

**Comment by calavera** [comment]
that could have been a typo. PRs very appreciated.

**Comment by kalinchernev** [comment]
Hi @calavera the thing is, I really don't know what is your intention with this task.
Feel free to just close the ticket.

**Comment by jhabdas** [comment]
@kalinchernev I just checked the git history and it looks like webpack dev server was replaced with browser sync in https://github.com/netlify/victor-hugo/commit/f85838665b07e62c79a56a6956f9a5c7d9a70ced#diff-ba210a9157252cc983268fdc3aa3ed52L15. IMHO that's a good thing. Just looks like that task was missed during the the changes. Think you could create a pull request against this repo to remove the unnecessary script from the package manifest?

**Comment by calavera** [comment]
> you could create a pull request against this repo to remove the unnecessary script from the package manifest

this sounds good to me.

**Comment by kalinchernev** [comment]
Hi @calavera @jhabdas PR is open ;)
Not an expert in this toolchain yet, but I plan to experiment a bit with webpack if it can handle the reload part, and if not probably just separate the browser-sync in a task and `npm-all` it.
But again, not an expert, just feeling a bit weird mixing the toolchain in such a way.
