### ISSUE TITLE
postcss: @apply rules won't find @imported css

### ISSUE THREAD

**Issue by barrabinfc** [netlify/victor-hugo#22]
There's an ordering error with `postcss-next` and `postcss-import`.

# Behaviour

If you have custom properties sets on a individual `@import`ed file, `postcss-apply` will fail to find them.
The following message will appear on console: 
```
...
postcss-apply: ...src/css/main.css:24:3: No custom properties set declared for `hero-font`.
...
```
# How to fix

Thankfully, it's an easy fix.
Just swap the order, they're processed in your `gulpfile.babel.js`, letting `cssImport` first.
```javascript
gulp.task("css", () => (
  gulp.src("./src/css/*.css")
    .pipe(postcss([cssImport({from: "./src/css/main.css"}), cssnext()]))
    .pipe(gulp.dest("./dist/css"))
    .pipe(browserSync.stream())
));
```
# Test example:
 
### File: src/css/imports/rules.css
```css
:root {
   --hero-font: {
    font-family: 'Antic', sans-serif;
    font-size: 2em;
  };
}
```
### File: src/css/main.css
```css
@import "imports/rules.css";

h1 {
   @apply --hero-font;
}
```

**Comment by jhabdas** [comment]
> Thankfully, it's an easy fix.

Why the issues template has a <q>How to fix</q> section is beyond me. @barrabinfc have you looked at [hugulp](https://github.com/jbrodriguez/hugulp) as a potential alternative to Webpack?

**Comment by calavera** [comment]
Thanks a lot for your clear description @barrabinfc. I've opened #23 to use your suggestion.
