### ISSUE TITLE
using pug and stylus

### ISSUE THREAD

**Issue by jaubut** [netlify/victor-hugo#35]
I tried to add a gulp task to use pug as my templating engine.. but it looks like hugo task is above it.. is it possible ?

**Comment by erquhart** [comment]
If you create additional tasks, just add them to the list of build tasks here: https://github.com/netlify/victor-hugo/blob/2207d3be5526fcc69cbf71974e9fca53468ef535/gulpfile.babel.js#L25-L26

If your tasks need to run before others, you'll need to change your Gulp config to run tasks in series, which there are plugins for. We should probably get this thing off of Gulp and use Webpack for everything, that would help a ton.
