### ISSUE TITLE
npm ERR! Error: No compatible version found: babel-plugin-transform-object-assign@'^6.8.0'

### ISSUE THREAD

**Issue by benamir** [netlify/victor-hugo#43]
[victor-hugo-master(__git_ps1 " (%s)")]$ npm install
npm http GET https://registry.npmjs.org/babel-eslint
npm http GET https://registry.npmjs.org/babel-plugin-syntax-object-rest-spread
npm http GET https://registry.npmjs.org/babel-plugin-transform-class-properties
npm http GET https://registry.npmjs.org/babel-plugin-transform-object-assign
npm http GET https://registry.npmjs.org/babel-loader
npm http GET https://registry.npmjs.org/babel-plugin-transform-object-rest-spread
npm http GET https://registry.npmjs.org/babel-register
npm http GET https://registry.npmjs.org/css-loader
npm http GET https://registry.npmjs.org/browser-sync
npm http GET https://registry.npmjs.org/eslint
npm http GET https://registry.npmjs.org/babel-preset-es2015
npm http GET https://registry.npmjs.org/exports-loader
npm http GET https://registry.npmjs.org/file-loader
npm http GET https://registry.npmjs.org/gulp-babel
npm http GET https://registry.npmjs.org/gulp-postcss
npm http GET https://registry.npmjs.org/gulp-util
npm http GET https://registry.npmjs.org/hugo-bin
npm http GET https://registry.npmjs.org/imports-loader
npm http GET https://registry.npmjs.org/eslint-plugin-import
npm http GET https://registry.npmjs.org/gulp
npm http GET https://registry.npmjs.org/url-loader
npm http GET https://registry.npmjs.org/postcss-cssnext
npm http GET https://registry.npmjs.org/postcss-import
npm http GET https://registry.npmjs.org/whatwg-fetch
npm http GET https://registry.npmjs.org/webpack
npm http 304 https://registry.npmjs.org/babel-plugin-transform-object-assign
npm http 304 https://registry.npmjs.org/babel-plugin-syntax-object-rest-spread
npm ERR! Error: No compatible version found: babel-plugin-transform-object-assign@'^6.8.0'
npm ERR! Valid install targets:
npm ERR! ["6.0.2","6.0.14","6.1.4","6.1.17","6.1.18","6.2.4","6.3.13","6.5.0","6.5.0-1","6.8.0","6.22.0","7.0.0-alpha.1","7.0.0-alpha.3","7.0.0-alpha.7","7.0.0-alpha.8","7.0.0-alpha.9","7.0.0-alpha.10","7.0.0-alpha.11","7.0.0-alpha.12","7.0.0-alpha.14","7.0.0-alpha.15","7.0.0-alpha.16","7.0.0-alpha.17","7.0.0-alpha.18","7.0.0-alpha.19","7.0.0-alpha.20"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:506:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:386:15
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:136:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR!  [Error: No compatible version found: babel-plugin-transform-object-assign@'^6.8.0'
npm ERR! Valid install targets:
npm ERR! ["6.0.2","6.0.14","6.1.4","6.1.17","6.1.18","6.2.4","6.3.13","6.5.0","6.5.0-1","6.8.0","6.22.0","7.0.0-alpha.1","7.0.0-alpha.3","7.0.0-alpha.7","7.0.0-alpha.8","7.0.0-alpha.9","7.0.0-alpha.10","7.0.0-alpha.11","7.0.0-alpha.12","7.0.0-alpha.14","7.0.0-alpha.15","7.0.0-alpha.16","7.0.0-alpha.17","7.0.0-alpha.18","7.0.0-alpha.19","7.0.0-alpha.20"]]
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 15.6.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/macuser/victor-hugo-master
npm ERR! node -v v0.8.0
npm ERR! npm -v 1.1.32
npm ERR! message No compatible version found: babel-plugin-transform-object-assign@'^6.8.0'
npm ERR! message Valid install targets:
npm ERR! message ["6.0.2","6.0.14","6.1.4","6.1.17","6.1.18","6.2.4","6.3.13","6.5.0","6.5.0-1","6.8.0","6.22.0","7.0.0-alpha.1","7.0.0-alpha.3","7.0.0-alpha.7","7.0.0-alpha.8","7.0.0-alpha.9","7.0.0-alpha.10","7.0.0-alpha.11","7.0.0-alpha.12","7.0.0-alpha.14","7.0.0-alpha.15","7.0.0-alpha.16","7.0.0-alpha.17","7.0.0-alpha.18","7.0.0-alpha.19","7.0.0-alpha.20"]
npm http 304 https://registry.npmjs.org/babel-eslint
npm http 304 https://registry.npmjs.org/babel-register
npm http 304 https://registry.npmjs.org/css-loader
npm http 304 https://registry.npmjs.org/eslint
npm http 304 https://registry.npmjs.org/babel-plugin-transform-class-properties
npm http 304 https://registry.npmjs.org/babel-loader
npm http 304 https://registry.npmjs.org/babel-plugin-transform-object-rest-spread
npm http 304 https://registry.npmjs.org/babel-preset-es2015
npm http 304 https://registry.npmjs.org/exports-loader
npm http 304 https://registry.npmjs.org/gulp-util
npm http 304 https://registry.npmjs.org/gulp-babel
npm http 304 https://registry.npmjs.org/browser-sync
npm http 304 https://registry.npmjs.org/hugo-bin
npm http 304 https://registry.npmjs.org/imports-loader
npm http 304 https://registry.npmjs.org/eslint-plugin-import
npm http 304 https://registry.npmjs.org/url-loader
npm http 304 https://registry.npmjs.org/postcss-cssnext
npm http 304 https://registry.npmjs.org/file-loader
npm http 304 https://registry.npmjs.org/gulp-postcss
npm http 304 https://registry.npmjs.org/postcss-import
npm http 304 https://registry.npmjs.org/webpack
npm http 304 https://registry.npmjs.org/gulp
npm http 304 https://registry.npmjs.org/whatwg-fetch
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/macuser/victor-hugo-master/npm-debug.log
npm ERR! not ok code 0

**Comment by jhabdas** [comment]
`npm i -g yarn`

**Comment by benamir** [comment]
Hi jhabdas, now I am getting the following: 

npm ERR! Error: No compatible version found: bytes@'^2.4.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.2.1","0.3.0","1.0.0","2.0.0","2.0.1","2.0.2","2.1.0","2.2.0","2.3.0","2.4.0","2.5.0","3.0.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:506:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:386:15
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:136:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR!  [Error: No compatible version found: bytes@'^2.4.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.2.1","0.3.0","1.0.0","2.0.0","2.0.1","2.0.2","2.1.0","2.2.0","2.3.0","2.4.0","2.5.0","3.0.0"]]
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 15.6.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "yarn"
npm ERR! cwd /Users/macuser/victor-hugo-master
npm ERR! node -v v0.8.0
npm ERR! npm -v 1.1.32
npm ERR! message No compatible version found: bytes@'^2.4.0'
npm ERR! message Valid install targets:
npm ERR! message ["0.0.1","0.1.0","0.2.0","0.2.1","0.3.0","1.0.0","2.0.0","2.0.1","2.0.2","2.1.0","2.2.0","2.3.0","2.4.0","2.5.0","3.0.0"]

**Comment by benamir** [comment]
npm ERR! Error: No compatible version found: babel-eslint@'^6.1.2'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.6","1.0.7","1.0.8","1.0.9","1.0.10","1.0.11","1.0.12","1.0.13","1.0.14","2.0.0","2.0.2","3.0.0","3.0.1","3.1.0","3.1.1","3.1.3","3.1.4","3.1.5","3.1.6","3.1.7","3.1.8","3.1.9","3.1.10","3.1.11","3.1.12","3.1.13","3.1.14","3.1.15","3.1.16","3.1.17","3.1.18","3.1.19","3.1.20","3.1.21","3.1.22","3.1.23","3.1.24","3.1.25","3.1.26","3.1.27","4.0.0","4.0.1","4.0.2","3.1.28","4.0.3","3.1.29","4.0.4","3.1.30","4.0.5","4.0.6","4.0.7","4.0.8","4.0.9","4.0.10","4.1.0","4.1.1","4.1.2","4.1.3","4.1.4","4.1.5","4.1.6","5.0.0-beta1","5.0.0-beta2","5.0.0-beta3","5.0.0-beta4","5.0.0-beta5","5.0.0-beta6","5.0.0-beta7","5.0.0-beta8","5.0.0-beta9","4.1.7","5.0.0-beta10","4.1.8","5.0.0","6.0.0-beta.1","6.0.0-beta.2","6.0.0-beta.3","6.0.0-beta.4","6.0.0-beta.5","6.0.0-beta.6","5.0.1","6.0.0","5.0.2","5.0.3","6.0.1","6.0.2","5.0.4","6.0.3","6.0.4","6.0.5","6.1.0","6.1.1","6.1.2"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:506:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:386:15
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:136:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR!  [Error: No compatible version found: babel-eslint@'^6.1.2'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.6","1.0.7","1.0.8","1.0.9","1.0.10","1.0.11","1.0.12","1.0.13","1.0.14","2.0.0","2.0.2","3.0.0","3.0.1","3.1.0","3.1.1","3.1.3","3.1.4","3.1.5","3.1.6","3.1.7","3.1.8","3.1.9","3.1.10","3.1.11","3.1.12","3.1.13","3.1.14","3.1.15","3.1.16","3.1.17","3.1.18","3.1.19","3.1.20","3.1.21","3.1.22","3.1.23","3.1.24","3.1.25","3.1.26","3.1.27","4.0.0","4.0.1","4.0.2","3.1.28","4.0.3","3.1.29","4.0.4","3.1.30","4.0.5","4.0.6","4.0.7","4.0.8","4.0.9","4.0.10","4.1.0","4.1.1","4.1.2","4.1.3","4.1.4","4.1.5","4.1.6","5.0.0-beta1","5.0.0-beta2","5.0.0-beta3","5.0.0-beta4","5.0.0-beta5","5.0.0-beta6","5.0.0-beta7","5.0.0-beta8","5.0.0-beta9","4.1.7","5.0.0-beta10","4.1.8","5.0.0","6.0.0-beta.1","6.0.0-beta.2","6.0.0-beta.3","6.0.0-beta.4","6.0.0-beta.5","6.0.0-beta.6","5.0.1","6.0.0","5.0.2","5.0.3","6.0.1","6.0.2","5.0.4","6.0.3","6.0.4","6.0.5","6.1.0","6.1.1","6.1.2"]]
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 15.6.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/macuser/victor-hugo-master
npm ERR! node -v v0.8.0
npm ERR! npm -v 1.1.32
npm ERR! message No compatible version found: babel-eslint@'^6.1.2'
npm ERR! message Valid install targets:
npm ERR! message ["1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.6","1.0.7","1.0.8","1.0.9","1.0.10","1.0.11","1.0.12","1.0.13","1.0.14","2.0.0","2.0.2","3.0.0","3.0.1","3.1.0","3.1.1","3.1.3","3.1.4","3.1.5","3.1.6","3.1.7","3.1.8","3.1.9","3.1.10","3.1.11","3.1.12","3.1.13","3.1.14","3.1.15","3.1.16","3.1.17","3.1.18","3.1.19","3.1.20","3.1.21","3.1.22","3.1.23","3.1.24","3.1.25","3.1.26","3.1.27","4.0.0","4.0.1","4.0.2","3.1.28","4.0.3","3.1.29","4.0.4","3.1.30","4.0.5","4.0.6","4.0.7","4.0.8","4.0.9","4.0.10","4.1.0","4.1.1","4.1.2","4.1.3","4.1.4","4.1.5","4.1.6","5.0.0-beta1","5.0.0-beta2","5.0.0-beta3","5.0.0-beta4","5.0.0-beta5","5.0.0-beta6","5.0.0-beta7","5.0.0-beta8","5.0.0-beta9","4.1.7","5.0.0-beta10","4.1.8","5.0.0","6.0.0-beta.1","6.0.0-beta.2","6.0.0-beta.3","6.0.0-beta.4","6.0.0-beta.5","6.0.0-beta.6","5.0.1","6.0.0","5.0.2","5.0.3","6.0.1","6.0.2","5.0.4","6.0.3","6.0.4","6.0.5","6.1.0","6.1.1","6.1.2"]

**Comment by jhabdas** [comment]
@benamir sux. sorry brah. maybe a leftpad?

**Comment by bdougie** [comment]
Can you provide context @benamir: What OSX, node, and npm versions are you using.

**Comment by erquhart** [comment]
@benamir you're running a very old version of npm my friend. I believe you're seeing an issue that was fixed [years ago](https://github.com/npm/npm/issues/4587#issuecomment-35370453) in npm 1.4.3. Updating should resolve it.
