### ISSUE TITLE
Adding new pages

### ISSUE THREAD

**Issue by Dazdd** [netlify/victor-hugo#58]
Im using hugo boiler plate for my new website. I do not need to use a theme, im happy to use the boilerplate setup.

One thing that is very unclear to me is how to setup and add new pages. I have built a components page within my index.html, I would like to now split up the pages, 

Can anyone please point me in the right direction

Cheers

**Comment by anagio** [comment]
@Dazdd this isn't an issue with victor hugo. Try asking at https://discourse.gohugo.io/

**Comment by erquhart** [comment]
Yep, this is a Hugo thing - victor-hugo is just a basic boilerplate, and doesn't alter the way you use Hugo. In addition to the discourse link provided above, check out their docs on [creating pages](https://gohugo.io/templates/single-page-templates/).
