### ISSUE TITLE
Recommended way to run Hugo CLI in victor-hugo?

### ISSUE THREAD

**Issue by 01ivr3** [netlify/victor-hugo#77]
What's the recommended way to use the hugo cli from within a victor-hugo project? 

It appears newer versions of victor-hugo switched to the hugo-bin package. I've tried running hugo cli via /node_modules/hugo-bin and hugo cli installed globally. In both cases I received errors; not being able to locate site's config, or something like that.

Apologies for such a silly question. I know this should probably be obvious.

**Comment by midzer** [comment]
I don't understand your question properly.
For development you just use `npm start` in root folder.
If you want any special Hugo behaviour with vector-hugo boilerplate, you have to modify it's task runner file `gulpfile.babel.js`.

**Comment by 01ivr3** [comment]
@midzer example: https://gohugo.io/commands/hugo_new/

**Comment by midzer** [comment]
Okay, in this case you better use your global Hugo binary, I think.
On the other hand, you could still modify `package.json` and add addition commands via `script` entry.

**Comment by 01ivr3** [comment]
Apologies, must have been doing something wrong before. Using the global Hugo binary from the project route to create new content files is working fine now.

**Comment by corford** [comment]
I also wondered about a clean way to do this (feels like it would be nice for victor hugo to support it). The solution was to change the command for the"hugo" script in package.json to.

`"hugo":` "node_modules/.bin/hugo --source site/"`

Then you can issue the following command (from your project root) to create a new page:
`npm run hugo -- new post/i-love-victor-hugo.md`
