### ISSUE TITLE
Unable to add a theme.

### ISSUE THREAD

**Issue by bdougie** [netlify/victor-hugo#8]
I have a student trying out this project and adding a theme to his victor-hugo project, however the page renders blank. https://github.com/Chammz/hugo-portfolio

Should `--theme=hugo-strata` to the gulp config? 

cc/ @Chammz

**Comment by bdougie** [comment]
I think the info here is sufficient to degbug, I can assist in debugging with you @Chammz

https://www.netlify.com/blog/2016/09/21/a-step-by-step-guide-hugo-on-netlify/

**Comment by jhabdas** [comment]
@bdougie the link provided is broken. Is there another link?

**Comment by bdougie** [comment]
@jhabdas I added a redirect to https://www.netlify.com/blog/2016/09/21/a-step-by-step-guide-victor-hugo-on-netlify/ which is the correct link.

**Comment by jhabdas** [comment]
Thanks, @bdougie 😺
