### ISSUE TITLE
How to start 'hugo server --buildDrafts'?

### ISSUE THREAD

**Issue by lichtner** [netlify/victor-hugo#88]
Sorry for simple question, but I don't find it in readme.

For development, I usually use `hugo server --buildDrafts` but I don't know how to do it with victor-hugo. Could you help me? Thanks.

**Comment by erquhart** [comment]
Use `npm run build-preview`, which runs `hugo server --buildDrafts --buildFuture`:

https://github.com/netlify/victor-hugo/blob/3668131f2ec0003bef94b4f33543f8844f7a0abd/gulpfile.babel.js#L15-L21

**Comment by lichtner** [comment]
but `npm run build-preview` just build preview and then stop. It is not able to use it for continual development. `hugo server -D` run server and keep it alive and reload after something is changed. I missed something like `npm run start-preview`. Is it a way for it?

**Comment by erquhart** [comment]
Might be good to accept a flag that sets `--buildDrafts` on the `gulp server` task if you want to submit a pull request.

If you want to get it working for yourself right now, I believe replacing `hugo` with `hugo-preview` in the tasks array for `gulp serve` would work:

https://github.com/netlify/victor-hugo/blob/3668131f2ec0003bef94b4f33543f8844f7a0abd/gulpfile.babel.js#L59
